# Generated by Django 5.2.4 on 2025-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(help_text="Persentase 1–100")),
                (
                    "icon",
                    models.CharField(
                        help_text="Contoh: devicon-python-plain", max_length=100
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="live_demo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(
                help_text="Contoh: Django, Tailwind", max_length=100
            ),
        ),
    ]
