# Generated by Django 5.2.4 on 2025-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_skill_project_github_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.CharField(default="No description provided.", max_length=255),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon_url",
            field=models.URLField(default="https://via.placeholder.com/40?text="),
        ),
    ]
