# Generated by Django 5.2.4 on 2025-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_name_skill_title_remove_skill_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="live_demo_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="project",
            name="alt_text",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="detail_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="repo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                default="", help_text="Comma separated, e.g. HTML,CSS", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="project-thumbnail/"),
        ),
    ]
