# Generated by Django 5.2.4 on 2025-07-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_project_github_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                default="General",
                help_text="e.g. Web Development, UI/UX Design",
                max_length=100,
            ),
        ),
    ]
